
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

// Removed typed Database import because the types file is read-only and empty,
// which caused supabase.from() to accept only 'never'.
// import type { Database } from './types';

const SUPABASE_URL = "https://epjspezpwezwfbzwybtq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVwanNwZXpwd2V6d2Ziend5YnRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2OTMwMTgsImV4cCI6MjA3MTI2OTAxOH0.lSvSTkWI09gT0yleJQIeUUMGlR9rTQCYpJMDARoxwqE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create an untyped Supabase client to avoid 'relation: never' errors due to empty schema types.
export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
