name: Build and FTP deploy to Hostinger (manager)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Vite project (force dist/)
        run: |
          npm run build -- --outDir dist
          echo "== Conteúdo da pasta dist =="
          ls -la dist || true

      - name: Add .htaccess and version.txt
        run: |
          echo 'Options -Indexes
          RewriteEngine On
          RewriteBase /
          RewriteRule ^index\.html$ - [L]
          RewriteCond %{REQUEST_FILENAME} !-f
          RewriteCond %{REQUEST_FILENAME} !-d
          RewriteRule . /index.html [L]' > dist/.htaccess
          
          echo "Build from GitHub Actions on $(date)" > dist/version.txt

      - name: Show output contents
        run: ls -la dist

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          local-dir: dist/
          server-dir: public_html/manager/
