name: Build and FTP deploy to Hostinger (main)

on:
  push:
    branches: ["main"]
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Vite project
        run: npm run build

      # Cria .htaccess (SPA) e um version.txt para checagem no navegador
      - name: Add htaccess and version stamp
        run: |
          cat << 'EOF' > dist/.htaccess
          RewriteEngine On
          RewriteBase /
          RewriteRule ^index\.html$ - [L]
          RewriteCond %{REQUEST_FILENAME} !-f
          RewriteCond %{REQUEST_FILENAME} !-d
          RewriteRule . /index.html [L]
          EOF
          date -u +"%Y-%m-%dT%H:%M:%SZ" > dist/version.txt

      - name: Deploy to Hostinger via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 147.93.42.93
          username: u887144620
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          protocol: ftps
          security: loose
          local-dir: dist/
          # Seu usuário FTP inicia em public_html, então publicamos só em "manager/"
          server-dir: manager/
          dangerous-clean-slate: true
