name: Build and FTP deploy to Hostinger (with htaccess)

on:
  push:
    branches: ["main"]
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Puxar o código do repositório
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configurar Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3. Instalar dependências
      - name: Install dependencies
        run: npm install

      # 4. Build do projeto (Vite)
      - name: Build Vite project
        run: npm run build

      # 5. Criar .htaccess dentro da pasta dist/ para subdomínio
      - name: Add .htaccess for subdomain SPA routes
        run: |
          cat << 'EOF' > dist/.htaccess
          RewriteEngine On
          RewriteBase /manager/
          RewriteRule ^index\.html$ - [L]
          RewriteCond %{REQUEST_FILENAME} !-f
          RewriteCond %{REQUEST_FILENAME} !-d
          RewriteRule . /manager/index.html [L]
          EOF

      # 6. Deploy via FTP para a Hostinger
      - name: Deploy to Hostinger via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 147.93.42.93
          username: u887144620
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          protocol: ftps
          security: loose
          local-dir: dist/
          server-dir: manager/
          dangerous-clean-slate: true
